#!/usr/bin/env bash
# go to the next song in the playlist for the currently playing mpv instance

IFS=$'\n'
declare -a PLAYING

abort() {
  echo 'No active instances of mpv...' >&2
  exit 1
}

read -r -d '' -a PLAYING < <(mpv-currently-playing --socket && printf '\0')

[[ "${#PLAYING[@]}" -eq 0 ]] && abort

mpv_prev() {
  mpv-communicate "$1" '{ "command": ["playlist-prev"] }'
  [[ -n "$2" ]] && shift
  mpv-track "$1"
}

[[ "$#" -eq 0 ]] && {
  mpv_prev "${PLAYING[-1]}"
  exit
}

# shellcheck disable=SC2207
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -f|--fzf)
      FZF="--fzf"
      shift
      ;;
    -m|--music)
      mpv_prev --music "${MPV_MUSIC_SOCKET:-${MPV_SOCKET_DIR:-/tmp/mpvSockets}/music_socket}"
      shift
      ;;
    -p|--pick)
      CHOSEN="$(mpv-pick $FZF --quiet)"
      [[ -z "$CHOSEN" ]] && {
        echo "No socket selected..." >&2
        exit 1
      }
      mpv_prev "$CHOSEN"
      shift
      ;;
    -s|--socket)
      shift
      [[ -z "$1" ]] && {
        echo "USAGE: --socket needs a socket"
        exit 1
      }
      mpv_prev "$1"
      shift
      ;;
    -u|--umpv)
      mpv_prev --umpv "${MPV_UMPV_SOCKET:-${MPV_SOCKET_DIR:-/tmp/mpvSockets}/umpv_socket}"
      shift
      ;;
    *)
      echo "Unrecognized option(s): $*..." >&2
      exit 1
      ;;
  esac
done
